# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  google_client_id: <%= ENV["GOOGLE_OAUTH_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_OAUTH_CLIENT_SECRET"] %>

development:
  <<: *default
  secret_key_base: 0d464fb7a45d46367f1f0d4612a0b8d911310c10833b1c419f73497bfd924ca7690067af6520877268fde6e2d871753740815652e921af0350b045ed703b8d4e

test:
  <<: *default
  secret_key_base: e8a06d776ea87a5abe2566886976fa6f4990d26c3a78dd7c469d790e691eabaa90f0837326084d1e591217e956bf299a9c091b53b0cda2c4f67a0e17f6f8a1df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
